### ISSUE TITLE
Support data downloads to devices

### ISSUE THREAD

**Issue by JimCAtSentosa** [cablelabs/lpwanserver#13]
Wasn't in the prototype that I recall, but useful functionality.

**Comment by dschrimpsher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LPWan: Finish Medium Priority Issues](https://trello.com/c/q6HdVjtt/17-lpwan-finish-medium-priority-issues)

**Comment by rhythnic** [comment]
Exists now at POST `/devices/:deviceId/downlinks`
