### ISSUE TITLE
Add ability for GlobalAdmin user to create Applications/Users/DeviceProfiles under any Company

### ISSUE THREAD

**Issue by JimCAtSentosa** [cablelabs/lpwanserver#14]
- companyId in POSTed data.
  - init to current user's companyId
- Add company selection list to UI if GlobalAdmin.
- Ensure stores handle correctly (UserStore already does - adds logged in user's companyId if not there.

**Comment by dschrimpsher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LPWan: Finish Medium Priority Issues](https://trello.com/c/q6HdVjtt/17-lpwan-finish-medium-priority-issues)
