### ISSUE TITLE
Fix TheThingsNetwork.js

### ISSUE THREAD

**Issue by rhythnic** [cablelabs/lpwanserver#202]
@dschrimpsher I had done a bunch of refactors inside of networkProtocols/TheThingsNetwork.js as part of #170 that I need for the browser tests to work.  I can see that the changes were merged into master in PR #175, but now master branch is as if that file wasn't merged.  I'm not sure how it happened, but I need to re-merge those changes in order to fix the TTN portion of the automated browser tests.  I see that you recently changed some things in that file to fix your e2e tests.  I'm going to try to start with my refactor as a baseline and add your changes and see if your e2e tests pass, then I'll do a PR.

**Comment by dschrimpsher** [comment]
Ok
