### ISSUE TITLE
Update Lora Server to ChirpStack in docs

### ISSUE THREAD

**Issue by rhythnic** [cablelabs/lpwanserver#345]

**Comment by luketainton** [comment]
I'll do some work on this.

**Comment by rhythnic** [comment]
@luketainton Thank you very much for helping out.  This is a priority, and I have time right now, so I'll go ahead and do it.  It also involves publishing the docs and updating the seed data, neither of which have clear documentation around the processes.  I think that #316 would be a good first issue.  FYI I'm pushing to get v2 ready for release, so most work will branch off of the v2 branch and then will merge back into v2.
