### ISSUE TITLE
Assessment & Design – Working with CableLabs, Assess impact of Things and Loriot on the Lora data model:

### ISSUE THREAD

**Issue by dschrimpsher** [cablelabs/lpwanserver#39]
- [x] Study Things/Loriot spec/docs/code to determine unique data requirements not covered by the current Lora JSON definition
- [x] Design decision: if there are significant new data model requirements
  1. expand the current JSON definition  
  2. create new Network Types

**Comment by SteveAtSentosa** [comment]
Attached Documents outline the design decisions made for adding Things/Loriot to LPWAN.
![lpwan-arch-add-loriot-things](https://user-images.githubusercontent.com/5873306/43169637-13d6847c-8f5f-11e8-8cfe-6a4b31aa763d.png)

[things-use-cases-ui-impact.txt](https://github.com/cablelabs/lpwanserver/files/2225699/things-use-cases-ui-impact.txt)

[loriot-use-cases-ui-impact.txt](https://github.com/cablelabs/lpwanserver/files/2225702/loriot-use-cases-ui-impact.txt)
